#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tinycompress
Version  : 1.2.3
Release  : 3
URL      : https://github.com/alsa-project/tinycompress/archive/v1.2.3/tinycompress-1.2.3.tar.gz
Source0  : https://github.com/alsa-project/tinycompress/archive/v1.2.3/tinycompress-1.2.3.tar.gz
Summary  : Tinycompress library for ALSA compress audio offload
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: tinycompress-bin = %{version}-%{release}
Requires: tinycompress-lib = %{version}-%{release}
Requires: tinycompress-license = %{version}-%{release}
BuildRequires : pkgconfig(libavcodec)

%description
=======================
vkoul@kernel.org
================
1. WHAT
tinycompress is a userspace library for anyone who wants to use the ALSA
compressed APIs introduced in Linux 3.3
This library provides the APIs to open a ALSA compressed device and read/write
compressed data like MP3 etc to it.

%package bin
Summary: bin components for the tinycompress package.
Group: Binaries
Requires: tinycompress-license = %{version}-%{release}

%description bin
bin components for the tinycompress package.


%package dev
Summary: dev components for the tinycompress package.
Group: Development
Requires: tinycompress-lib = %{version}-%{release}
Requires: tinycompress-bin = %{version}-%{release}
Provides: tinycompress-devel = %{version}-%{release}
Requires: tinycompress = %{version}-%{release}

%description dev
dev components for the tinycompress package.


%package lib
Summary: lib components for the tinycompress package.
Group: Libraries
Requires: tinycompress-license = %{version}-%{release}

%description lib
lib components for the tinycompress package.


%package license
Summary: license components for the tinycompress package.
Group: Default

%description license
license components for the tinycompress package.


%prep
%setup -q -n tinycompress-1.2.3
cd %{_builddir}/tinycompress-1.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1591819635
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1591819635
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tinycompress
cp %{_builddir}/tinycompress-1.2.3/COPYING %{buildroot}/usr/share/package-licenses/tinycompress/2bc63ab4d970d91a85c6d0fd3759700019415640
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cplay
/usr/bin/crecord

%files dev
%defattr(-,root,root,-)
/usr/include/tinycompress/tinycompress.h
/usr/lib64/libtinycompress.so
/usr/lib64/pkgconfig/tinycompress.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtinycompress.so.0
/usr/lib64/libtinycompress.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tinycompress/2bc63ab4d970d91a85c6d0fd3759700019415640
